version: '3.3'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  env_file:
  - ./.env.dev
  volumes:
  - ./app:/app
  - ./log:/app/log

 mysqldb:
  image: mysql
  ports:
  - 3307:3306
  env_file:
  - ./.env.db
  volumes:
  - ./init:/docker-entrypoint-initdb.d
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: