version: '3.3'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./app:/app

 mysqldb:
  image: mysql
  ports:
  - 3307:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - ./init:/docker-entrypoint-initdb.d
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: